apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: oracle-pg
    url: postgres:5432
    user: postgres
    database: oracle_index
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: postgres
    isDefault: true
    editable: false
